name: PR
run-name: ${{ github.actor }} is testing out GitHub Actions, additional task
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - test1
jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
    - run: echo The PR was merged